### ISSUE TITLE
Upgrade to xterm.js 4.14 when it ships

### ISSUE THREAD

**Issue by Tyriar** [OmarTawfik/terminal-screenshot#7]
Just came across this, very cool 🙂 

FYI we recently implemented custom glyphs for box drawing and block elements which will make your readme images much more fancy.

![image](https://user-images.githubusercontent.com/2193314/131539202-8294839d-0d76-4189-b76b-fc425c5bdb6f.png)
![image](https://user-images.githubusercontent.com/2193314/131539213-bd41363a-681a-4b4a-aaa1-7d9ca0f581da.png)

I'm going to try get the release done this week sometime.

**Comment by OmarTawfik** [comment]
@Tyriar Awesome. Thanks for the heads up!

**Comment by edouard-lopez** [comment]
Bump, latest [xterm.js](https://github.com/xtermjs/xterm.js/) is `5.3.0` any plan to update?
